/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VisualLayer;

/**
 *
 * @author David B
 */
public class UserInterface extends javax.swing.JFrame {

    /**
     * Creates new form Sign_Layer
     */
    public UserInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Frame_SignIn = new javax.swing.JFrame();
        Layered_Unchangable_SignIn = new javax.swing.JLayeredPane();
        Panel_SignIn_Head = new javax.swing.JPanel();
        Layered_SignIn_PanelBase = new javax.swing.JLayeredPane();
        Layered_Unchangable_Main = new javax.swing.JLayeredPane();
        Panel_Main_Head = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Layered_Main_PanelBase = new javax.swing.JLayeredPane();
        Panel_MainMenu = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Panel_Prestamos = new javax.swing.JPanel();
        Panel_LibroDetalle = new javax.swing.JPanel();
        Panel_UsuarioDetalle = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        Frame_SignIn.setMaximumSize(new java.awt.Dimension(600, 400));
        Frame_SignIn.setMinimumSize(new java.awt.Dimension(600, 400));
        Frame_SignIn.setResizable(false);

        Layered_Unchangable_SignIn.setMaximumSize(new java.awt.Dimension(600, 400));
        Layered_Unchangable_SignIn.setMinimumSize(new java.awt.Dimension(600, 400));
        Layered_Unchangable_SignIn.setLayout(new java.awt.BorderLayout());

        Panel_SignIn_Head.setBackground(new java.awt.Color(45, 49, 66));
        Panel_SignIn_Head.setMaximumSize(new java.awt.Dimension(600, 100));
        Panel_SignIn_Head.setMinimumSize(new java.awt.Dimension(600, 100));

        javax.swing.GroupLayout Panel_SignIn_HeadLayout = new javax.swing.GroupLayout(Panel_SignIn_Head);
        Panel_SignIn_Head.setLayout(Panel_SignIn_HeadLayout);
        Panel_SignIn_HeadLayout.setHorizontalGroup(
            Panel_SignIn_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        Panel_SignIn_HeadLayout.setVerticalGroup(
            Panel_SignIn_HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Layered_Unchangable_SignIn.add(Panel_SignIn_Head, java.awt.BorderLayout.PAGE_START);

        Layered_SignIn_PanelBase.setBackground(new java.awt.Color(191, 192, 192));
        Layered_SignIn_PanelBase.setMaximumSize(new java.awt.Dimension(600, 300));
        Layered_SignIn_PanelBase.setMinimumSize(new java.awt.Dimension(600, 300));

        javax.swing.GroupLayout Layered_SignIn_PanelBaseLayout = new javax.swing.GroupLayout(Layered_SignIn_PanelBase);
        Layered_SignIn_PanelBase.setLayout(Layered_SignIn_PanelBaseLayout);
        Layered_SignIn_PanelBaseLayout.setHorizontalGroup(
            Layered_SignIn_PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        Layered_SignIn_PanelBaseLayout.setVerticalGroup(
            Layered_SignIn_PanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        Layered_Unchangable_SignIn.add(Layered_SignIn_PanelBase, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout Frame_SignInLayout = new javax.swing.GroupLayout(Frame_SignIn.getContentPane());
        Frame_SignIn.getContentPane().setLayout(Frame_SignInLayout);
        Frame_SignInLayout.setHorizontalGroup(
            Frame_SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layered_Unchangable_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Frame_SignInLayout.setVerticalGroup(
            Frame_SignInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layered_Unchangable_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 550));

        Layered_Unchangable_Main.setMaximumSize(new java.awt.Dimension(900, 550));
        Layered_Unchangable_Main.setMinimumSize(new java.awt.Dimension(900, 550));
        Layered_Unchangable_Main.setPreferredSize(new java.awt.Dimension(900, 550));
        Layered_Unchangable_Main.setLayout(new java.awt.BorderLayout());

        Panel_Main_Head.setBackground(new java.awt.Color(251, 133, 0));
        Panel_Main_Head.setMaximumSize(new java.awt.Dimension(900, 100));
        Panel_Main_Head.setMinimumSize(new java.awt.Dimension(900, 100));
        Panel_Main_Head.setPreferredSize(new java.awt.Dimension(900, 100));
        Panel_Main_Head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Main Menu");
        Panel_Main_Head.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 670, 100));

        Layered_Unchangable_Main.add(Panel_Main_Head, java.awt.BorderLayout.PAGE_START);

        Layered_Main_PanelBase.setMaximumSize(new java.awt.Dimension(900, 450));
        Layered_Main_PanelBase.setMinimumSize(new java.awt.Dimension(900, 450));
        Layered_Main_PanelBase.setPreferredSize(new java.awt.Dimension(900, 450));

        Panel_MainMenu.setBackground(new java.awt.Color(2, 48, 71));
        Panel_MainMenu.setMaximumSize(new java.awt.Dimension(900, 450));
        Panel_MainMenu.setMinimumSize(new java.awt.Dimension(900, 450));
        Panel_MainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("My Account");
        jButton3.setMaximumSize(new java.awt.Dimension(250, 300));
        jButton3.setMinimumSize(new java.awt.Dimension(250, 300));
        jButton3.setPreferredSize(new java.awt.Dimension(250, 300));
        Panel_MainMenu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 260, -1));

        jButton5.setText("My Account");
        jButton5.setMaximumSize(new java.awt.Dimension(250, 300));
        jButton5.setMinimumSize(new java.awt.Dimension(250, 300));
        jButton5.setPreferredSize(new java.awt.Dimension(250, 300));
        Panel_MainMenu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        jButton6.setText("My Account");
        jButton6.setMaximumSize(new java.awt.Dimension(250, 300));
        jButton6.setMinimumSize(new java.awt.Dimension(250, 300));
        jButton6.setPreferredSize(new java.awt.Dimension(250, 300));
        Panel_MainMenu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        Layered_Main_PanelBase.add(Panel_MainMenu);
        Panel_MainMenu.setBounds(0, 0, 900, 450);

        Panel_Prestamos.setMaximumSize(new java.awt.Dimension(900, 450));
        Panel_Prestamos.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout Panel_PrestamosLayout = new javax.swing.GroupLayout(Panel_Prestamos);
        Panel_Prestamos.setLayout(Panel_PrestamosLayout);
        Panel_PrestamosLayout.setHorizontalGroup(
            Panel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Panel_PrestamosLayout.setVerticalGroup(
            Panel_PrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(Panel_Prestamos);
        Panel_Prestamos.setBounds(0, 0, 900, 450);

        Panel_LibroDetalle.setMaximumSize(new java.awt.Dimension(900, 450));
        Panel_LibroDetalle.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout Panel_LibroDetalleLayout = new javax.swing.GroupLayout(Panel_LibroDetalle);
        Panel_LibroDetalle.setLayout(Panel_LibroDetalleLayout);
        Panel_LibroDetalleLayout.setHorizontalGroup(
            Panel_LibroDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Panel_LibroDetalleLayout.setVerticalGroup(
            Panel_LibroDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(Panel_LibroDetalle);
        Panel_LibroDetalle.setBounds(0, 0, 900, 450);

        Panel_UsuarioDetalle.setMaximumSize(new java.awt.Dimension(900, 450));
        Panel_UsuarioDetalle.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout Panel_UsuarioDetalleLayout = new javax.swing.GroupLayout(Panel_UsuarioDetalle);
        Panel_UsuarioDetalle.setLayout(Panel_UsuarioDetalleLayout);
        Panel_UsuarioDetalleLayout.setHorizontalGroup(
            Panel_UsuarioDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        Panel_UsuarioDetalleLayout.setVerticalGroup(
            Panel_UsuarioDetalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(Panel_UsuarioDetalle);
        Panel_UsuarioDetalle.setBounds(0, 0, 900, 450);

        jPanel5.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel5.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel5);
        jPanel5.setBounds(0, 0, 900, 450);

        jPanel6.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel6.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel6);
        jPanel6.setBounds(0, 0, 900, 450);

        jPanel7.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel7.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel7);
        jPanel7.setBounds(0, 0, 900, 450);

        jPanel8.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel8.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel8);
        jPanel8.setBounds(0, 0, 900, 450);

        jPanel9.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel9.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel9);
        jPanel9.setBounds(0, 0, 900, 450);

        jPanel10.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel10.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel10);
        jPanel10.setBounds(0, 0, 900, 450);

        jPanel11.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel11.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel11);
        jPanel11.setBounds(0, 0, 900, 450);

        jPanel12.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel12.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel12);
        jPanel12.setBounds(0, 0, 900, 450);

        jPanel13.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel13.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel13);
        jPanel13.setBounds(0, 0, 900, 450);

        jPanel14.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel14.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel14);
        jPanel14.setBounds(0, 0, 900, 450);

        jPanel15.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel15.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel15);
        jPanel15.setBounds(0, 0, 900, 450);

        jPanel16.setMaximumSize(new java.awt.Dimension(900, 450));
        jPanel16.setMinimumSize(new java.awt.Dimension(900, 450));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        Layered_Main_PanelBase.add(jPanel16);
        jPanel16.setBounds(0, 0, 900, 450);

        Layered_Unchangable_Main.add(Layered_Main_PanelBase, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Layered_Unchangable_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Layered_Unchangable_Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Frame_SignIn;
    private javax.swing.JLayeredPane Layered_Main_PanelBase;
    private javax.swing.JLayeredPane Layered_SignIn_PanelBase;
    private javax.swing.JLayeredPane Layered_Unchangable_Main;
    private javax.swing.JLayeredPane Layered_Unchangable_SignIn;
    private javax.swing.JPanel Panel_LibroDetalle;
    private javax.swing.JPanel Panel_MainMenu;
    private javax.swing.JPanel Panel_Main_Head;
    private javax.swing.JPanel Panel_Prestamos;
    private javax.swing.JPanel Panel_SignIn_Head;
    private javax.swing.JPanel Panel_UsuarioDetalle;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
