------Desde SYS
CREATE TABLESPACE LOANLIBRARY_Data
DATAFILE 'C:\app\Junior\oradata\orcl\LOANLIBRARY01.dbf'
SIZE 10M
REUSE
AUTOEXTEND ON
NEXT 512k
MAXSIZE 200M;
--
-- PE: Index
--
CREATE TABLESPACE LOANLIBRARY_Ind
       DATAFILE 'C:\app\Junior\oradata\orcl\LOANLIBRARY_IND01.dbf'
       SIZE 10M
       REUSE
       AUTOEXTEND ON
       NEXT 512k
       MAXSIZE 200M;