----DESDE SYS
CREATE USER loanlibrary
       IDENTIFIED BY loanlibrary
       DEFAULT TABLESPACE LOANLIBRARY_Data
       QUOTA 10M ON LOANLIBRARY_Data
       TEMPORARY TABLESPACE temp
       QUOTA 5M ON system;
       
GRANT CONNECT TO loanlibrary;
GRANT CREATE ANY TABLE TO loanlibrary;